#You should rename this file to "config.aml"

#Discord bot settings

BOT:
  #bot token
  token: ""


  #bot client id
  client_id: 1919810114514228922

  #The Discord ids who own the bot.
  owner_ids:
    - 123123123123123123
    - 222312340875029525
  #The role id who can use admin commands.
  role_ids:
    - 029384570239092434


  #Lavalink server
  #Some public servers
  #https://lavalink.darrennathanael.com/
Lavalink:
  Host: "aitronlavalink.tk"
  Port: 443
  Password: "aitronbots.tk"
  Secure: True
